In [48]:
import pandas as pd
import re

In [49]:
df = pd.read_csv("Customer Call List.csv")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,NaN,NaN
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,NaN,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,NaN,NaN
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN

In [50]:
df=df.drop_duplicates()

In [51]:
df=df.drop(columns =["Unnamed: 8"])

In [52]:
df=df.drop(columns =["Unnamed: 9"])

In [53]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [54]:
import re

def clean_name(x):
    return re.sub(r"[^\w\s]", "", str(x))

df["clean_last_name"] = df["Last_Name"].apply(clean_name)

In [55]:
df["clean_last_name"]=df["Last_Name"].apply(clean_name)

In [56]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,clean_last_name
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,Baggins
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,Nadir
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,White
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,Schrute
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,Snow
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,Swanson
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,Winger
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,Holmes
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,nan
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,Parker
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,Gamgee
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,Potter
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,Draper
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,Knope
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,Flenderson_
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,Weasley
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,Scott
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,Kent
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,Braton
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,Skywalker

In [57]:
def clean_name1(x):
    return re.sub(r"[^\w\s]", "", str(x)).replace("_", "")

In [58]:
df["clean_last_name"]=df["clean_last_name"].apply(clean_name1)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,clean_last_name
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,Baggins
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,Nadir
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,White
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,Schrute
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,Snow
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,Swanson
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,Winger
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,Holmes
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,nan
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,Parker
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,Gamgee
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,Potter
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,Draper
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,Knope
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,Flenderson
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,Weasley
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,Scott
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,Kent
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,Braton
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,Skywalker

In [59]:
def clean_number(x):
    return re.sub(r"[^0-9]","",str(x))

In [60]:
df["clean_Phone_Number"]=df["Phone_Number"].apply(clean_number)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,clean_last_name,clean_Phone_Number
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,Baggins,1235455421
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,Nadir,1236439775
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,White,7066950392
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,Schrute,1235432345
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,Snow,8766783469
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,Swanson,3047622467
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,Winger,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,Holmes,8766783469
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,nan,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,Parker,1235455421
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,Gamgee,
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,Potter,7066950392
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,Draper,1235432345
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,Knope,8766783469
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,Flenderson,3047622467
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,Weasley,1235455421
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,Scott,1236439775
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,Kent,7066950392
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,Braton,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,Skywalker,8766783469

In [61]:
df[["clean_houseno.","clean_street"]]=df["Address"].str.split(" ",n=1,expand =True)

In [62]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,White,7066950392,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,Schrute,1235432345,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,Braton,,N/a,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [63]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("yes","y")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,White,7066950392,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,Schrute,1235432345,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,Braton,,N/a,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [64]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("No","N")

In [65]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,White,7066950392,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,Schrute,1235432345,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,False,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,N,True,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,Braton,,N/a,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [66]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("Yes","y")

In [67]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,y,False,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,White,7066950392,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,Schrute,1235432345,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,y,True,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,False,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,N,True,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,N/a,N/a,N/a,y,True,Braton,,N/a,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [68]:
df=df.drop(columns = "Not_Useful_Column")

In [69]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,y,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,White,7066950392,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Schrute,1235432345,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,y,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,N,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,N/a,N/a,N/a,y,Braton,,N/a,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [70]:
df["Paying Customer"]=df["Paying Customer"].str.replace("Yes","Y")

In [71]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,y,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,White,7066950392,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Schrute,1235432345,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,y,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Y,NaN,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Y,N,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,N/a,N/a,N/a,y,Braton,,N/a,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [72]:
df["Paying Customer"]=df["Paying Customer"].str.replace("No","N")

In [73]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,N,y,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,White,7066950392,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Schrute,1235432345,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,y,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,NaN,1209 South Street,N,N,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Y,NaN,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Y,N,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,N/a,N/a,N/a,y,Braton,,N/a,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [81]:
df=df.replace("N/a","")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,N,y,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,White,7066950392,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Schrute,1235432345,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,y,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,NaN,1209 South Street,N,N,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Y,N,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,,,,y,Braton,,,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [82]:
df=df.fillna("")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,N,y,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,White,7066950392,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Schrute,1235432345,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,y,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,,1209 South Street,N,N,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,,,123 Middle Earth,Y,,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,,,,y,Braton,,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [86]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"]=='Y':
        df.drop(x,inplace =True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,N,y,Nadir,1236439775,93,West Main Street
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,White,7066950392,298,Drugs Driveway
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,y,Swanson,3047622467,768,City Parkway
6,1007,Jeff,Winger,,1209 South Street,N,N,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,,,123 Middle Earth,Y,,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,Kent,7066950392,3498,Super Lane
18,1019,Creed,Braton,,,,y,Braton,,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [87]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"]=='y':
        df.drop(x,inplace =True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,White,7066950392,298,Drugs Driveway
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
6,1007,Jeff,Winger,,1209 South Street,N,N,Winger,,1209,South Street
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
8,1009,Gandalf,,,123 Middle Earth,Y,,nan,,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,Gamgee,,612,"Shire Lane, Shire"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,Kent,7066950392,3498,Super Lane
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [88]:
for x in df.index:
    if df.loc[x,"clean_Phone_Number"]=='':
        df.drop(x,inplace =True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,White,7066950392,298,Drugs Driveway
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,Potter,7066950392,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Weasley,1235455421,2395,Hogwarts Avenue
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,Kent,7066950392,3498,Super Lane
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [89]:
df=df.reset_index(drop=True)

In [90]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
1,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,White,7066950392,298,Drugs Driveway
2,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
3,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
4,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
5,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,Potter,7066950392,2394,Hogwarts Avenue
6,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
7,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
8,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
9,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Weasley,1235455421,2395,Hogwarts Avenue
10,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
11,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,Kent,7066950392,3498,Super Lane
12,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [91]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"]=='':
        df.drop(x,inplace =True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
2,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
3,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
4,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
6,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
7,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
8,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
9,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Weasley,1235455421,2395,Hogwarts Avenue
10,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
12,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [92]:
df=df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
1,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,Snow,8766783469,123,Dragons Road
2,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,Holmes,8766783469,98,Clue Drive
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Parker,1235455421,25th,"Main Street, New York"
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Draper,1235432345,2039,Main Street
5,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,Knope,8766783469,343,City Parkway
6,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,Flenderson,3047622467,214,HR Avenue
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Weasley,1235455421,2395,Hogwarts Avenue
8,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
9,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [94]:
df.drop(columns=["Last_Name", "Phone_Number", "Address"], inplace=True)

In [95]:
df

,CustomerID,First_Name,Paying Customer,Do_Not_Contact,clean_last_name,clean_Phone_Number,clean_houseno.,clean_street
0,1001,Frodo,Y,N,Baggins,1235455421,123,"Shire Lane, Shire"
1,1005,Jon,Y,N,Snow,8766783469,123,Dragons Road
2,1008,Sherlock,N,N,Holmes,8766783469,98,Clue Drive
3,1010,Peter,Y,N,Parker,1235455421,25th,"Main Street, New York"
4,1013,Don,Y,N,Draper,1235432345,2039,Main Street
5,1014,Leslie,Y,N,Knope,8766783469,343,City Parkway
6,1015,Toby,N,N,Flenderson,3047622467,214,HR Avenue
7,1016,Ron,N,N,Weasley,1235455421,2395,Hogwarts Avenue
8,1017,Michael,Y,N,Scott,1236439775,121,"Paper Avenue, Pennsylvania"
9,1020,Anakin,Y,N,Skywalker,8766783469,910,"Tatooine Road, Tatooine"

In [ ]:
## here it ends